[package]
name = "p0287_find_duplicate_number"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rstest = "0.18.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


