[workspace]
members = [
    "p0001_two_sum", "p0049_group_anagrams",
    "p0049_group_anagrams",
    "p0217_contains_duplicate",
    "p0242_valid_anagram",
    "p0287_find_duplicate_number",
]
resolver = "2"
