[project]
name = "python"
version = "0.1.0"
description = "LeetCode Solutions and tests using Python"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = ["coverage>=7.7.1", "pytest>=8.3.5"]

[tool.pytest.ini_options]
pythonpath = ["."]
