[package]
name = "p0001_two_sum"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14"

[dev-dependencies]
rstest = "0.18.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"